### ISSUE TITLE
Problem on AddAlleleBalance

### ISSUE THREAD

**Issue by moneterg** [ThomasLudwig/VCFProcessor#1]
Hi @ThomasLudwig 

First, I would like to thank you for program availability. It helped a lot!

Further, I'm here to ask some help about function "AddAlleleBalance".

I have a multisample VCF (~450 samples) and I used this function to calculate "AB" annotation for each sample (on FORMAT field) in order to filter my variants based on some annotation cutoffs established by me.

Apparently, the program ran ok.
But, when I ran a second tool "bcftools query", problems appeared on some lines related to "AB" field.
So then, I realized that for samples with missing genotypes, "AB" annotation weren't added.

Here I put some snippet from my VCF with some problems I've found. Problems are in bold format.

<pre>
chr1	880238	rs3748592	A	G	(...)	GT:AD:DP:GQ:PGT:PID:PL:AB	1/1:0,31:31:93:.:.:1312,93,0:.	0/1:18,10:28:99:.:.:335,0,645:0.643	<b>./.:2,0:2:.:.:.:0,0,0</b>	0/0:44,0:44:99:.:.:0,111,1665:. 
chr1	896064	rs113034360	C	G	(...)	GT:AD:DP:GQ:PL:AB	0/0:3,0:3:9:0,9,90:.	<b>./.:0,0:0:.:0,0,0</b>	0/1:5,5:10:79:113,0,79:0.500	1/1:0,2:2:6:49,6,0:.
chr1	897641	rs181477281	C	T	(...)	GT:AD:DP:GQ:PL:AB	0/0:17,0:17:51:0,51,711:.	<b>./.:0,0:0:.:0,0,0</b>	0/1:11,9:20:99:278,0,408:0.550	0/0:8,0:8:24:0,24,335:.
</pre>

I know that "./." is about missing genotypes. But, I couldn't remove all variants, since I would miss important information about other samples with GTs defined. For this same reason, I also couldn't remove samples with missing genotypes, since I would miss important information about other variants (with no "./.") on such samples.

So, maybe for such missing genotypes an "AB=." would be assigned, since downstream tools (like bcftools or other) will check for such field.

Well, I don't know if you already realized this or if I'm wrong. Maybe you could help me here.

Thank you very much for your time.

**Comment by ThomasLudwig** [comment]
Hi @Monete 

thank you for trying VCFProcessor and for bringing this bug to my attention.
It has been fixed in the release 1.0.2.

Feel free to report further problems and also if you find that some functions that might be useful for your work are missing. I mostly implement functions that I need and might not have thought of some things useful to other researchers.

Cheers

Thomas

**Comment by moneterg** [comment]
Hi @ThomasLudwig 
Thank you for fixing this.

As far as I know, this AB annotation has been deleted from new GATK version and I didn't find any other tool which calculated it.
That's why this tool is helping a lot.

Further, I'd like to take the opportunity about AB annotation, to highlight something that I realized today.
I think AB calculation here is different from previous versions from GATK.

They calculate like this (AlleleBalanceBySample - Allele balance per sample):
AB = \frac{# ALT alleles}{total # alleles}

And I think the calculation made in VCFProcessor take REF alleles into account, like this:
AB = Ref AD / Total AD

Actually, I don't know if there is a convention about this calculation.
Even so, could you please confirm/clarify this for me?

Thank you very much for your time and help.

Best

Monete

**Comment by ThomasLudwig** [comment]
Hi @Monete 

The calculation in VCFProcessor is : 
AB = alleleDepth(gt1) / (alleleDepth(gt1) + alleleDepth(gt2))
so it can vary from GATK's depending on the number of ALTs and the genotype (0/1; 0|1;1|0)

in case of a 0/1 genotype, if your formula for GATK is correct and the variant is biallelic, the results should be the same
